### ISSUE TITLE
Check in Cargo.lock

### ISSUE THREAD

**Issue by jcgruenhage** [davidpob99/nasa-wallpaper#12]
To quote from the [`cargo` FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries):
> it is recommended that all binaries check in their Cargo.lock.

**Comment by davidpob99** [comment]
Thank you for pointing it out, I am going to update all the dependencies and then publish `Cargo.lock` file
