### ISSUE TITLE
error (main thread panic) when passing '-t' flag

### ISSUE THREAD

**Issue by larsthegeek** [davidpob99/nasa-wallpaper#7]
Hi, I've noticed an issue when attempting to change the background image using the '-t' (title) flag.  This is occuring for me on OSX Mojave (10.14.6).

When using the command: `RUST_BACKTRACE=1 nasa-wallpaper -n -t 'NGC949'`, I get an error:

```Changing wallpaper...
thread 'main' panicked at 'No items were found :(', src/main.rs:174:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: nasa_wallpaper::main
   8: std::rt::lang_start::{{closure}}
   9: std::rt::lang_start_internal
  10: main
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.`
```

However, when using the nearly identical command: `RUST_BACKTRACE=1 nasa-wallpaper -n -t 'hubble'`, the background changes successfully.

Perhaps an issue when no results are returned or the results contain an unsupported character?

Cheers

**Comment by stonespheres** [comment]
> Hi, I've noticed an issue when attempting to change the background image using the '-t' (title) flag. This is occuring for me on OSX Mojave (10.14.6).
> 
> When using the command: `RUST_BACKTRACE=1 nasa-wallpaper -n -t 'NGC949'`, I get an error:
> 
> ```
> thread 'main' panicked at 'No items were found :(', src/main.rs:174:9
> stack backtrace:
>    0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
>    1: core::fmt::write
>    2: std::io::Write::write_fmt
>    3: std::panicking::default_hook::{{closure}}
>    4: std::panicking::default_hook
>    5: std::panicking::rust_panic_with_hook
>    6: std::panicking::begin_panic
>    7: nasa_wallpaper::main
>    8: std::rt::lang_start::{{closure}}
>    9: std::rt::lang_start_internal
>   10: main
> note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.`
> ```
> 
> However, when using the nearly identical command: `RUST_BACKTRACE=1 nasa-wallpaper -n -t 'hubble'`, the background changes successfully.
> 
> Perhaps an issue when no results are returned or the results contain an unsupported character?
> 
> Cheers

`panic!` Is an error handling call used when the error is unrecoverable. I'm having a look at this to see if there's a better way to handle an error if `*num_hits == 0`

**Comment by davidpob99** [comment]
Hello, first of all I would like to apologize for not having maintained this project for the last few years, I will try to be more active in this project in the future.

Secondly, thanks for the contributions, you are totally right that I should not have used `panic!` when no results are obtained, I am going to merge the changes.

**Comment by stonespheres** [comment]
> Hello, first of all I would like to apologize for not having maintained this project for the last few years, I will try to be more active in this project in the future.
Welcome back! I'd actually forgotten about the project, so it was a nice surprise to see my inbox light up! Looking forward to seeing where this goes!

> Secondly, thanks for the contributions, you are totally right that I should not have used `panic!` when no results are obtained, I am going to merge the changes.
Thank you for the merge!
