### ISSUE TITLE
Wallpaper only works when 'image' selected in Plasma wallpaper settings

### ISSUE THREAD

**Issue by stonespheres** [davidpob99/nasa-wallpaper#8]
Similar to #6, wallpaper settings were on dynamic. After changing these settings to 'Image' I was able to change the wallpaper.

**Comment by stonespheres** [comment]
This appears to be linked to how` wallpaper.rs` defines the wallpaper in `plasma-org.kde.plasma.desktop-appletsrc`. 
Having a look at my `plasma-org.kde.plasma.desktop-appletsrc` file, there are several definitions for wallpapers, `wallpaper.rs` seems to only set one of them.

**Comment by davidpob99** [comment]
Hi, thank you for reporting this (I do not use KDE).

Maybe is better to open an issue in the library's git to be solved for every app that uses it: https://github.com/reujab/wallpaper.rs. In the meantime I think the fastest patch is to advise users in the readme about this behavior
